module.exports = {

    staticAssetsRoot: '/exa_modules/billing/static',

    moduleNames: {
        setup: 'setup',
        claim: 'claims',
        claims: 'claims',
        payment: 'payments',
        payments: 'payments',
        pending_payments: 'payments',
        era: 'era',
        edi: 'edi',
    },

    screenNames: {
        'adjustment_codes': 'Adjustment Codes',
        'billing_codes': 'Billing Codes',
        'cas_group_codes': 'CAS Group Codes',
        'cas_reason_codes': 'CAS Reason Codes',
        'billing_providers': 'Billing Providers',
        'billing_classes': 'Billing Classes',
        'provider_id_code_qualifiers': 'Provider ID Code Qualifiers',
        'provider_id_codes': 'Provider ID Codes',
        'paper_claim_printer_setup': 'Paper Claim Printer Setup',
        'provider_level_codes': 'Provider Level Codes',
        'claim_status': 'Claim Status',
        'billing_messages': 'Billing Messages',
        'payment_reasons': 'Payment Reasons',
        'validations': 'Validations',
        'edi_clearinghouses': 'EDI Clearinghouses',
        'status_color_codes': 'Status Color Codes',
        'x12': 'EDI Templates',
        'insurance_x12_mapping': 'Insurance X12 Mapping',
        'user_log' : 'User Log',
        'audit_log': 'Audit Log',
        'printer_templates': 'Printer Templates',
        'payments': 'Payments',
        'applyPayments':'Applied Payments',
        'claim_inquiry':'Claim Inquiry',
        'claim':'Claims',
        'studies': 'Studies',
        'Payments': 'Edit Claim',
        'split_claim': 'Split Claim',
        'validate_claims': 'Validate Claims',
        'aged-ar-summary': 'Aged AR Summary',
        'aged-ar-details': 'Aged AR Details',
        'charges': 'Charge Report',
        'claim-activity': 'Claim Activity Report',
        'claim-transaction': 'Claim Transaction Report',
        'credit-balance-encounters': 'Credit Balance Encounters Report',
        'diagnosis-count': 'Diagnosis Count Report',
        'modality-summary': 'Modality Summary Report',
        'monthly-recap': 'Monthly Recap Report',
        'patient-statement': 'Patient Statment Report',
        'payer-mix': 'Payer Mix Report',
        // 'payment': 'Payments Report' Need to change the name,
        'claim-inquiry': 'Claim Inquiry Report',
        'insurance-vs-lop': 'Insurance Vs LOP Report',
        'patients-by-insurance-company': 'Patients by Insurance Company',
        'payments-by-ins-company': 'Payments by Insurance Company',
        'procedure-analysis-by-insurance': 'Procedure Analysis by Insurance Report',
        'procedure-count': 'Procedure Count Report',
        'reading-provider-fees': 'Reading Provider Fees Report',
        'referring-provider-count': 'Referring Provider Count Report',
        'referring-provider-summary': 'Referring Provider Summary Report',
        'transaction-summary': 'Transaction Summary Report'
    },

    entityNames: {
        adjustment_codes: 'adjustment_codes',
        billing_codes: 'billing_codes',
        cas_group_codes: 'cas_group_codes',
        cas_reason_codes: 'cas_reason_codes',
        billing_providers: 'billing_providers',
        billing_classes: 'billing_classes',
        provider_id_code_qualifiers: 'provider_id_code_qualifiers',
        provider_id_codes: 'provider_id_codes',
        paper_claim_printer_setup: 'paper_claim_printer_setup',
        provider_level_codes: 'provider_level_codes',
        claim_status: 'claim_status',
        billing_messages: 'billing_messages',
        payment_reasons: 'payment_reasons',
        validations: 'validations',
        edi_clearinghouses: 'edi_clearinghouses',
        status_color_codes: 'status_color_codes',
        x12: 'edi_templates',
        insurance_x12_mapping: 'insurance_x12_mapping',
        printer_templates: 'printer_templates',
        payments: 'payments',
        applyPayments:'payment_applications',
        claim_inquiry:'claim_comments',
        audit_log: 'Audit Log',
        user_log: 'User Log',
        claims:'Claims'
    },

    permissionsMap: {
        'adjustment_codes': 'ADJC',
        'billing_codes': 'BICO',
        'billing_classes': 'BICL',
        'claim_status': 'CLST',
        'billing_providers': 'BIPR',
        'provider_id_code_qualifiers': 'PRCQ',
        'billing_messages': 'BILM',
        'payment_reasons': 'PARE',
        'cas_group_codes': 'CASG',
        'cas_reason_codes': 'CASR',
        'status_color_codes': 'STCC',
        'validations': 'BIVA',
        'printer_templates': 'PCA',
        'x12': 'EDRT',
        'insurance_x12_mapping': 'INSM',
        'edi_clearinghouses': 'CLHO',
        'user_log': 'BULG',
        'audit_log': 'BALG',
        'claim_workbench': 'CLIM',
        'claims_total_records': 'CLIM',
        'claim_filters': 'CLIM',
        'providers': 'CLIM', // AS OF NOW ---->  providers Auto Complete if claim have right then all drop will get rights
        'icd_codes':'CLIM', //Auto Cpmplete
        'provider_group': 'CLIM', //Auto Cpmplete
        'insurances': 'CLIM', //Auto Cpmplete
        'orderingFacility': 'CLIM', //Auto Cpmplete
        'patients': 'CLIM',  //Auto Cpmplete
        'getUsers': 'CLIM',  //Auto Cpmplete
        'autoCompleteRouter': 'CLIM', //Auto Cpmplete cpt code
        'getUserRoles': 'CLIM', //Auto Cpmplete
        'printer_template': 'CLIM', //when claim
        'invoice_data':'CLIM', //when claim
        'claim_json':'CLIM', //when claim
        'patient_insurances': 'CLIM', //create claim
        'line_items': 'CLIM', //create claim
        'studies': 'HSTY', 
        'study_filters': 'SFIL',
        'studies_total_records': 'HSTY',
        'payments': 'PAYM',
        'claim_inquiry': 'CLMI',
        'split_claim': 'MASO',
        'validate_claims': 'CLVA',
        'aged-ar-summary': 'AGAR',
        'aged-ar-details': 'AARD',
        'charges': 'CHRG',
        'claim-activity': 'CLAY',
        'claim-transaction': 'CLTR',
        'credit-balance-encounters': 'CRBE',
        'diagnosis-count': 'DICN',
        'modality-summary': 'MOSU',
        'monthly-recap': 'MNRC',
        'patient-statement': 'PATS',
        'payer-mix': 'PYMX',
        'patient-activity-statement': 'PACT',
        'payment-report':'PAYT',
        'claim-inquiry': 'CLIN',
        'insurance-vs-lop': 'IVSL',
        'patients-by-insurance-company': 'PAIC',
        'payments-by-ins-company': 'PBIC',
        'procedure-analysis-by-insurance': 'PABI',
        'procedure-count': 'PRCN',
        'reading-provider-fees': 'RPFR',
        'referring-provider-count': 'REPC',
        'referring-provider-summary': 'REPS',
        'transaction-summary': 'TSUM',
        'list': 'PAYM', // screenNameInternal = list for EOB doubts having
        'total_amount': 'PAYM',
        'groupcodes_and_reasoncodes': 'PAYM',
        'all': 'PAYM',
        'patient_count': 'PAYM',
        'patient_search': 'PAYM',
        'payment-receipt-pdf':'PAYM',
        'claim': 'ECLM',
        'billing_payers': 'ECLM',
        'service_facilities': 'ECLM',
        'transcription': 'ECLM',
        'vieworder': 'ECLM', // view doc Rmenu
        'claim_charge': 'ECLM', //delete Claim Rmenu 
        'upload': 'ERAI',
        'user_settings':'BUST',
        'claim_study': 'ECLM',
        'follow_ups': 'ECLM',
        'claim_patient': 'PCLM'
    }
};
