const XML_ELEMENTS = {
    LST: "LST",
    GRP: "GRP",
    FILE_HEADER: "FHS",
    XML_ROOT: "ZRPT_P03",
    WCB_NEW_CLAIM_TEMPLATE: "WCB_C568",
    WCB_CORRECTION_CLAIM_TEMPLATE: "WCB_C570",
    TRASACTION_SEGMENT: "ZRPT_P03.LST.1",
    CONTENT_NODE: "ZRPT_P03.LST.6",
    CONTENT_GRP_4: "ZRPT_P03.GRP.4",
    CONTENT_LST_5: "ZRPT_P03.LST.5",
    CONTENT_GRP_3: "ZRPT_P03.GRP.3",
    CONTENT_GRP_2: "ZRPT_P03.GRP.2",
    CONTENT_LST_3: "ZRPT_P03.LST.3",
    CONTENT_GRP_1: "ZRPT_P03.GRP.1",
    CONTENT_LST_1: "ZRPT_P03.LST.1",
    INVOICE_TYPE_CODE: "FT1.6",
    TRANSACTION_CODE: "FT1.7",
    TRANSACTION_DESCRIPTION: "FT1.8",
    FILE_TRAILER: "FTS",
    BATCH_HEADER: "BHS",
    BATCH_TRAILER: "BTS",
    PATIENT_SEGMENT: "PID",
    PATIENT_VIST_SEGMENT: "PV1",
    INVOICE_LINE_SEGMENT: "FT1",
    ICD_POB_SEGMENT: "FT1.19",
    FEE_MODIFIER_SEGMENT: "FT1.26",
    PROVIDER_SEGMENT: "PRD",
    ATTACHMENT_SEGMENT: "OBX",
    MESSAGE_HEADER: "MSH",
    EVENT_SEGMENT: "EVN",
    REF_PROV_SEGMENT: "RF1",
    PATIENT_SEGMENT: "PID",
    ACCIDENT_SEGMENT: "ACC",
    NAMESPACE: "urn:WCBhl7_v231-schema_modern_v100",
    XMLSCHEMA_INSTANCE: "http://www.w3.org/2001/XMLSchema-instance",
    XMLSCHEMA_INSTANCE_LOCATION: "urn:WCBhl7_v231-schema_modern_v100./WCBhl7_v231_modern_v100.xsd",
};

const COUNTRY_CODES = {
    "can": "CN",
    "usa": "US"
};

module.exports = {
    XML_ELEMENTS,
    COUNTRY_CODES
};
