const wcbParser = require('../../../../../modules/ahs/wcb/wcb-parser');
const chai = require('chai');
const config = require('../../../../../server/config');
config.initialize();
describe('Get claims record from WCB remittance file', () => {
    it('should return array of parsed xml remittance data', async () => {
        var fileData = `<?xml version="1.0" encoding="utf-8"?>
            <PaymentRemittanceReport SortSelection1="Disbursement Number" SortSelection2="" SortSelection3="" xmlns="http://www.wcb.ab.ca/schemas/RR/RRPaymentRemittanceReport-2.01.00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wcb.ab.ca/schemas/RR/RRPaymentRemittanceReport-2.01.00 Schema_RRPaymentRemittanceReport_2_01_00.xsd">
            <ReportWeek>
            <StartDate>2009-04-25</StartDate>
            <EndDate>2009-05-01</EndDate>
            </ReportWeek>
            <PaymentRemittanceRecord>
                <DisbursementNumber>4185300</DisbursementNumber>
                <DisbursementType>EFT</DisbursementType>
                <DisbursementIssueDate>2009-05-06</DisbursementIssueDate>
                <DisbursementXRefNumber/>
                <DisbursementAmount>1629.55</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>REQ</PaymentReasonCode>
                <PaymentStatus>ISS</PaymentStatus>
                <PaymentStartDate>2009-04-24</PaymentStartDate>
                <PaymentEndDate>2009-04-24</PaymentEndDate>
                <PaymentAmount>20.00</PaymentAmount>
                <ElectronicReportBilledAmount>234.34</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2080059</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-25</ElectronicReportSubmissionDate>
                <ClaimNumber>7655819</ClaimNumber>
                <WorkerPHN>795382030</WorkerPHN>
                <WorkerFirstName>Tom</WorkerFirstName>
                <WorkerLastName>Peterson</WorkerLastName>
                <WorkerMiddleInitial>M</WorkerMiddleInitial>
                <ServiceCode/>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls/>
                <EncounterNumber/>
                <OverpaymentRecoveryAmount>18.13</OverpaymentRecoveryAmount>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber>4185300</DisbursementNumber>
                <DisbursementType>EFT</DisbursementType>
                <DisbursementIssueDate>2009-05-06</DisbursementIssueDate>
                <DisbursementXRefNumber/>
                <DisbursementAmount>1629.55</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>REQ</PaymentReasonCode>
                <PaymentStatus>ISS</PaymentStatus>
                <PaymentStartDate>2009-04-29</PaymentStartDate>
                <PaymentEndDate>2009-04-29</PaymentEndDate>
                <PaymentAmount>20.00</PaymentAmount>
                <ElectronicReportBilledAmount>123.12</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2088808</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-30</ElectronicReportSubmissionDate>
                <ClaimNumber>9663150</ClaimNumber>
                <WorkerPHN>409636031</WorkerPHN>
                <WorkerFirstName>John</WorkerFirstName>
                <WorkerLastName>Louis</WorkerLastName>
                <WorkerMiddleInitial/>
                <ServiceCode/>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls/>
                <EncounterNumber/>
                <OverpaymentRecoveryAmount>2.87</OverpaymentRecoveryAmount>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber>4185301</DisbursementNumber>
                <DisbursementType>EFT</DisbursementType>
                <DisbursementIssueDate>2009-05-06</DisbursementIssueDate>
                <DisbursementXRefNumber/>
                <DisbursementAmount>2196.74</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>USR</PaymentReasonCode>
                <PaymentStatus>ISS</PaymentStatus>
                <PaymentStartDate>2009-04-21</PaymentStartDate>
                <PaymentEndDate>2009-04-21</PaymentEndDate>
                <PaymentAmount>36.19</PaymentAmount>
                <ElectronicReportBilledAmount>0</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>0</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate/>
                <ClaimNumber>8634527</ClaimNumber>
                <WorkerPHN>924731790</WorkerPHN>
                <WorkerFirstName>TONY</WorkerFirstName>
                <WorkerLastName>AKINS</WorkerLastName>
                <WorkerMiddleInitial>J</WorkerMiddleInitial>
                <ServiceCode>07.38AB</ServiceCode>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls>1.00</NumberOfCalls>
                <EncounterNumber>1</EncounterNumber>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber/>
                <DisbursementType/>
                <DisbursementIssueDate>2009-01-01</DisbursementIssueDate>
                <DisbursementXRefNumber/>
                <DisbursementAmount>0</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>USR</PaymentReasonCode>
                <PaymentStatus>PGA</PaymentStatus>
                <PaymentStartDate>2009-03-02</PaymentStartDate>
                <PaymentEndDate>2009-03-02</PaymentEndDate>
                <PaymentAmount>62.40</PaymentAmount>
                <ElectronicReportBilledAmount>62.40</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2063069</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-15</ElectronicReportSubmissionDate>
                <ClaimNumber>7641343</ClaimNumber>
                <WorkerPHN>161919710</WorkerPHN>
                <WorkerFirstName>LONI</WorkerFirstName>
                <WorkerLastName>BIBY</WorkerLastName>
                <WorkerMiddleInitial>L</WorkerMiddleInitial>
                <ServiceCode>07.38AA</ServiceCode>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls>1.00</NumberOfCalls>
                <EncounterNumber>1</EncounterNumber>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber/>
                <DisbursementType/>
                <DisbursementIssueDate/>
                <DisbursementXRefNumber/>
                <DisbursementAmount>0</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>D60</PaymentReasonCode>
                <PaymentStatus>REJ</PaymentStatus>
                <PaymentStartDate>2009-03-09</PaymentStartDate>
                <PaymentEndDate>2009-03-09</PaymentEndDate>
                <PaymentAmount>0</PaymentAmount>
                <ElectronicReportBilledAmount>62.40</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2064706</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-16</ElectronicReportSubmissionDate>
                <ClaimNumber>8584955</ClaimNumber>
                <WorkerPHN>183209710</WorkerPHN>
                <WorkerFirstName>Bill</WorkerFirstName>
                <WorkerLastName>Black</WorkerLastName>
                <WorkerMiddleInitial>G</WorkerMiddleInitial>
                <ServiceCode>07.38AA</ServiceCode>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls>1.00</NumberOfCalls>
                <EncounterNumber>1</EncounterNumber>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber/>
                <DisbursementType/>
                <DisbursementIssueDate/>
                <DisbursementXRefNumber/>
                <DisbursementAmount>0</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio </DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>USR</PaymentReasonCode>
                <PaymentStatus>PGA</PaymentStatus>
                <PaymentStartDate>2009-03-02</PaymentStartDate>
                <PaymentEndDate>2009-03-02</PaymentEndDate>
                <PaymentAmount>36.19</PaymentAmount>
                <ElectronicReportBilledAmount>36.19</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2063069</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-15</ElectronicReportSubmissionDate>
                <ClaimNumber>8641343</ClaimNumber>
                <WorkerPHN>161919710</WorkerPHN>
                <WorkerFirstName>LONI</WorkerFirstName>
                <WorkerLastName>BIBI</WorkerLastName>
                <WorkerMiddleInitial>L</WorkerMiddleInitial>
                <ServiceCode>07.38AB</ServiceCode>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls>1.00</NumberOfCalls>
                <EncounterNumber>1</EncounterNumber>
            </PaymentRemittanceRecord>
            <PaymentRemittanceRecord>
                <DisbursementNumber/>
                <DisbursementType/>
                <DisbursementIssueDate/>
                <DisbursementXRefNumber/>
                <DisbursementAmount>0</DisbursementAmount>
                <DisbursementRecipientBillingNumber>X090</DisbursementRecipientBillingNumber>
                <DisbursementRecipientName>Smith Physio</DisbursementRecipientName>
                <PaymentPayeeBillingNumber>X090</PaymentPayeeBillingNumber>
                <PaymentPayeeName>Smith Physio</PaymentPayeeName>
                <PaymentReasonCode>USR</PaymentReasonCode>
                <PaymentStatus>PGA</PaymentStatus>
                <PaymentStartDate>2009-04-15</PaymentStartDate>
                <PaymentEndDate>2009-04-15</PaymentEndDate>
                <PaymentAmount>36.19</PaymentAmount>
                <ElectronicReportBilledAmount>36.19</ElectronicReportBilledAmount>
                <ElectronicReportTransactionID>2085475</ElectronicReportTransactionID>
                <ElectronicReportTransactionSubmissionNumber/>
                <ElectronicReportBatchSubmissionNumber/>
                <ElectronicReportSubmissionDate>2009-04-29</ElectronicReportSubmissionDate>
                <ClaimNumber>9615091</ClaimNumber>
                <WorkerPHN>916845800</WorkerPHN>
                <WorkerFirstName>ANNA</WorkerFirstName>
                <WorkerLastName>CAINE</WorkerLastName>
                <WorkerMiddleInitial/>
                <ServiceCode>07.38AB</ServiceCode>
                <ModifierCode1/>
                <ModifierCode2/>
                <ModifierCode3/>
                <NumberOfCalls>1.00</NumberOfCalls>
                <EncounterNumber>1</EncounterNumber>
            </PaymentRemittanceRecord>
            <OverpaymentRemittanceRecord>
                <RecoveredOnDisbursementNumber>4185300</RecoveredOnDisbursementNumber>
                <OVPDisbursementPayeeBillingNumber>B8894625</OVPDisbursementPayeeBillingNumber>
                <OVPDisbursementPayeeName>Ron Smith</OVPDisbursementPayeeName>
                <OVPClaimNumber>2684123</OVPClaimNumber>
                <OVPWorkerPHN>481236710</OVPWorkerPHN>
                <OVPWorkerFirstName>Don</OVPWorkerFirstName>
                <OVPWorkerLastName>Little</OVPWorkerLastName>
                <OVPWorkerMiddleInitial>K</OVPWorkerMiddleInitial>
                <DateOfOverpayment>2006-01-09</DateOfOverpayment>
                <OVPReason>ENT</OVPReason>
                <RecoveryAmount>28.97</RecoveryAmount>
                <RecoveredFromClaimNumber>2994123</RecoveredFromClaimNumber>
                <RecoveredFromWorkerFirstName>Don</RecoveredFromWorkerFirstName>
                <RecoveredFromWorkerLastName>Little</RecoveredFromWorkerLastName>
                <RecoveredFromWorkerMiddleInitial>K</RecoveredFromWorkerMiddleInitial>
            </OverpaymentRemittanceRecord>
            <OverpaymentRemittanceRecord>
                <RecoveredOnDisbursementNumber/>
                <OVPDisbursementPayeeBillingNumber>B8894625</OVPDisbursementPayeeBillingNumber>
                <OVPDisbursementPayeeName>Ron Smith</OVPDisbursementPayeeName>
                <OVPClaimNumber>2684123</OVPClaimNumber>
                <OVPWorkerPHN>481236710</OVPWorkerPHN>
                <OVPWorkerFirstName>Don</OVPWorkerFirstName>
                <OVPWorkerLastName>Little</OVPWorkerLastName>
                <OVPWorkerMiddleInitial>K</OVPWorkerMiddleInitial>
                <DateOfOverpayment>2006-01-09</DateOfOverpayment>
                <OVPReason>DEL</OVPReason>
                <RecoveryAmount>22.13</RecoveryAmount>
            </OverpaymentRemittanceRecord>
            </PaymentRemittanceReport>`;

        const data = await wcbParser.getWCBData(fileData);
        chai.should().exist(fileData);
        data.should.be.an('object');
    });
});
